# Generated by Django 2.2.6 on 2020-05-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodeuct',
            new_name='Product',
        ),
    ]
